# Docker Compose for Aura AI
version: '3.8'

services:
  aura:
    build: .
    container_name: aura_ai
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./logs:/app/logs
      - ./memory:/app/memory
      - ./.env:/app/.env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11435
    depends_on:
      - searxng
    restart: unless-stopped
    networks:
      - aura_network

  searxng:
    image: searxng/searxng:latest
    container_name: aura_searxng
    ports:
      - "8088:8080"
    volumes:
      - ./docker/searxng/settings:/etc/searxng:rw
    environment:
      - SEARXNG_SECRET_KEY=change_me_to_something_random
    restart: unless-stopped
    networks:
      - aura_network

networks:
  aura_network:
    driver: bridge

volumes:
  aura_data:
  aura_db:
  aura_logs:
