# Lightweight configuration for Aura
version: '3'

networks:
  aura_network:
    driver: bridge

services:
  ollama:
    image: ollama/ollama
    container_name: aura_new
    ports:
      - "11435:11434"
    volumes:
      - D:/Docker/ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - aura_network

  ollama-webui:
    image: ollama/ollama-webui:latest
    container_name: ollama-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_HOST=http://aura_new:11434
    restart: unless-stopped
    networks:
      - aura_network

  searxng:
    image: searxng/searxng:latest
    container_name: searxng_aura
    ports:
      - "8088:8080"
    volumes:
      - ./docker/searxng/settings:/etc/searxng
    restart: unless-stopped
    networks:
      - aura_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - D:/Docker/qdrant:/qdrant/storage
    restart: unless-stopped
    networks:
      - aura_network
