# Docker Compose for Aura AI - Web API Mode
version: '3.8'

services:
  aura-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: aura_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./logs:/app/logs
      - ./memory:/app/memory
      - ./.env:/app/.env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11435
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    depends_on:
      - searxng
    restart: unless-stopped
    networks:
      - aura_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  searxng:
    image: searxng/searxng:latest
    container_name: aura_searxng
    ports:
      - "8088:8080"
    volumes:
      - ./docker/searxng/settings:/etc/searxng:rw
    environment:
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET:-change_me_to_something_random}
    restart: unless-stopped
    networks:
      - aura_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/search?q=test"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  aura_network:
    driver: bridge

volumes:
  aura_data:
    driver: local
  aura_db:
    driver: local
  aura_logs:
    driver: local
  aura_memory:
    driver: local
