version: '3'

services:
  searxng:
    container_name: searxng_aura
    image: searxng/searxng:latest
    ports:
      - "8088:8080"  # 将SearXNG的8080端口映射到主机的8088端口
    volumes:
      - ./settings:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8088/
      - INSTANCE_NAME=aura-search
    restart: unless-stopped
